### PR TITLE
changed = to ==

### PR DESCRIPTION
**Pull request by t-cool**

### CODE REVIEW

**Comment by yohasebe** [comment]
Thanks, again.

**Comment by yohasebe** [comment]
I once merged the change but later reverted. This change breaks spec tests. The `if` statements in question do not check equality but existence of a value. Thanks anyway for your attention to the code.

**Comment by t-cool** [comment]
Sorry for my mistake. Now I understand its behavior thanks to your advice!

**Comment by yohasebe** [comment]
Never mind! BTW I am sorry I couldn't respond to you when you requested for explanation about the code the other day. I'm glad to hear that you have a better grasp of the code now.

**Pull request merged**
